### ISSUE TITLE
Define the depedencies in requirements.txt or use a setup.py

### ISSUE THREAD

**Issue by santhoshtr** [sushant354/egazette#3]
So that the installation and usage is easy. 

I guess the requirements.txt would be like this
```
beautifulsoup4
python-magic
PyPDF2
Pillow
```

The tesseract dependecy would require mannual installation though

**Comment by sushant354** [comment]
Added here  https://github.com/sushant354/egazette/commit/cad2e4faf0bde0b16e0908eba4e66a18a43a4635
